# Generated by Django 5.0.14 on 2026-06-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Listing Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_per_kg_usd_cents', models.PositiveIntegerField(verbose_name='Price per kg (USD cents)')),
                ('quantity_available_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Available (kg)')),
                ('location_province', models.CharField(choices=[('HARARE', 'Harare'), ('BULAWAYO', 'Bulawayo'), ('MANICALAND', 'Manicaland'), ('MASHONALAND_CENTRAL', 'Mashonaland Central'), ('MASHONALAND_EAST', 'Mashonaland East'), ('MASHONALAND_WEST', 'Mashonaland West'), ('MASVINGO', 'Masvingo'), ('MATABELELAND_NORTH', 'Matabeleland North'), ('MATABELELAND_SOUTH', 'Matabeleland South'), ('MIDLANDS', 'Midlands')], max_length=50, verbose_name='Province')),
                ('location_district', models.CharField(max_length=100, verbose_name='District')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.category', verbose_name='Category')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'verbose_name': 'Retail Listing',
                'verbose_name_plural': 'Retail Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Wholesale Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('price_per_tonne_usd_cents', models.PositiveIntegerField(verbose_name='Price per Tonne (USD cents)')),
                ('quantity_available_tonnes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Available (Tonnes)')),
                ('min_order_quantity_tonnes', models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Minimum Order Quantity (Tonnes)')),
                ('quality_grade', models.CharField(choices=[('A', 'Grade A'), ('B', 'Grade B'), ('C', 'Grade C')], max_length=5, verbose_name='Quality Grade')),
                ('moisture_content_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Moisture Content (%)')),
                ('harvest_date', models.DateField(verbose_name='Harvest Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_listings', to='listings.category', verbose_name='Category')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wholesale_listings', to='market_data.commodity', verbose_name='Commodity')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_listings', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'verbose_name': 'Wholesale Listing',
                'verbose_name_plural': 'Wholesale Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='listings/images/', verbose_name='Image File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing', verbose_name='Retail Listing')),
                ('wholesale_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.wholesalelisting', verbose_name='Wholesale Listing')),
            ],
            options={
                'verbose_name': 'Listing Image',
                'verbose_name_plural': 'Listing Images',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
