# Generated by Django 5.0.14 on 2026-06-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_district', models.CharField(max_length=100, verbose_name='Origin District')),
                ('destination_district', models.CharField(max_length=100, verbose_name='Destination District')),
                ('total_weight_kg', models.PositiveIntegerField(verbose_name='Total Weight (kg)')),
                ('status', models.CharField(choices=[('OPEN', 'Open for Bookings'), ('BOOKED', 'Booked'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Logistics Pool',
                'verbose_name_plural': 'Logistics Pools',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoadPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.PositiveIntegerField(verbose_name='Weight (kg)')),
                ('origin_district', models.CharField(max_length=100, verbose_name='Origin District')),
                ('destination_district', models.CharField(max_length=100, verbose_name='Destination District')),
                ('target_pickup_date', models.DateField(verbose_name='Target Pickup Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open for Pooling'), ('POOLING', 'Pooling In Progress'), ('POOLED', 'Pooled'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='load_posts', to='market_data.commodity', verbose_name='Commodity')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_posts', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Load Post',
                'verbose_name_plural': 'Load Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_share_cents', models.PositiveIntegerField(verbose_name='Cost Share (USD cents)')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('load_post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pool_membership', to='logistics.loadpost', verbose_name='Load Post')),
                ('logistics_pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='logistics.logisticspool', verbose_name='Logistics Pool')),
            ],
            options={
                'verbose_name': 'Pool Membership',
                'verbose_name_plural': 'Pool Memberships',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company/Trading Name')),
                ('vehicle_type', models.CharField(max_length=100, verbose_name='Vehicle Type (e.g. 10-Tonne Truck)')),
                ('vehicle_capacity_kg', models.PositiveIntegerField(verbose_name='Vehicle Capacity (kg)')),
                ('license_number', models.CharField(max_length=50, verbose_name='Operator License Number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('rating', models.FloatField(default=5.0, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transporter',
                'verbose_name_plural': 'Transporters',
                'ordering': ['-rating', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='FleetBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Transporter Acceptance'), ('CONFIRMED', 'Confirmed'), ('IN_TRANSIT', 'In Transit'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Booking Status')),
                ('agreed_cost_cents', models.PositiveIntegerField(verbose_name='Agreed Cost (USD cents)')),
                ('booking_date', models.DateField(verbose_name='Scheduled Transport Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Booked By')),
                ('load_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='logistics.loadpost', verbose_name='Single Load Post')),
                ('logistics_pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='logistics.logisticspool', verbose_name='Logistics Pool')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='logistics.transporter', verbose_name='Transporter')),
            ],
            options={
                'verbose_name': 'Fleet Booking',
                'verbose_name_plural': 'Fleet Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
