# Generated by Django 5.0.14 on 2026-06-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Commodity Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Commodity',
                'verbose_name_plural': 'Commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, verbose_name='District / Market')),
                ('price_per_tonne_usd_cents', models.PositiveIntegerField(verbose_name='Price per Tonne (USD cents)')),
                ('recorded_date', models.DateField(verbose_name='Recorded Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market_data.commodity', verbose_name='Commodity')),
            ],
            options={
                'verbose_name': 'Commodity Price',
                'verbose_name_plural': 'Commodity Prices',
                'ordering': ['-recorded_date', 'commodity'],
            },
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='District / Market')),
                ('target_price_usd_cents', models.PositiveIntegerField(verbose_name='Target Price per Tonne (USD cents)')),
                ('alert_type', models.CharField(choices=[('ABOVE', 'Trigger Above Target'), ('BELOW', 'Trigger Below Target')], max_length=10, verbose_name='Alert Type')),
                ('is_triggered', models.BooleanField(default=False, verbose_name='Is Triggered')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='market_data.commodity', verbose_name='Commodity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Price Alert',
                'verbose_name_plural': 'Price Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_price_usd_cents', models.PositiveIntegerField(verbose_name='Average Price per Tonne (USD cents)')),
                ('volume_tonnes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Aggregated Volume (Tonnes)')),
                ('calculated_date', models.DateField(verbose_name='Calculated Date')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='market_data.commodity', verbose_name='Commodity')),
            ],
            options={
                'verbose_name': 'Price Index',
                'verbose_name_plural': 'Price Indices',
                'ordering': ['-calculated_date', 'commodity'],
            },
        ),
    ]
