# Generated by Django 5.0.14 on 2026-06-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='category',
            field=models.CharField(choices=[('GRAINS', 'Grains & Cereals'), ('LEGUMES', 'Legumes & Oilseeds'), ('HORTICULTURE', 'Horticulture (Fruits & Veg)'), ('LIVESTOCK', 'Livestock & Meat'), ('DAIRY', 'Dairy Products'), ('OTHER', 'Other Commercial')], default='GRAINS', max_length=50, verbose_name='Taxonomy Category'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='hs_code',
            field=models.CharField(blank=True, help_text='Harmonized System Code for international trade / exports', max_length=20),
        ),
        migrations.AddField(
            model_name='commodity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Disable to temporarily pause trading of this commodity platform-wide.'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='search_keys',
            field=models.CharField(blank=True, help_text='Comma-separated synonyms (e.g., maize, corn, chibage, umbila)', max_length=255),
        ),
        migrations.AddField(
            model_name='commodity',
            name='standard_unit',
            field=models.CharField(default='Tonnes', help_text='Standard trade metric (e.g., Tonnes, Kilograms, Bales, Head)', max_length=20),
        ),
    ]
