# Generated by Django 5.0.14 on 2026-06-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_tonne_usd_cents', models.PositiveIntegerField(verbose_name='Proposed Price per Tonne (USD cents)')),
                ('qty_tonnes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Proposed Quantity (Tonnes)')),
                ('deposit_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Proposed Deposit (%)')),
                ('terms_text', models.TextField(blank=True, verbose_name='Proposed Terms')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Is Rejected')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='contracts.bulkcontract', verbose_name='Bulk Contract')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Proposed By')),
            ],
            options={
                'verbose_name': 'Contract Proposal',
                'verbose_name_plural': 'Contract Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='Participants')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Message Text')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/', verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation', verbose_name='Conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
