# Generated by Django 5.0.14 on 2026-06-11 19:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialBuyerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150, verbose_name='Company Name')),
                ('company_registration_number', models.CharField(max_length=50, verbose_name='Registration Number')),
                ('buyer_type', models.CharField(choices=[('SUPERMARKET', 'Supermarket Chain'), ('FOOD_PROCESSOR', 'Food Processor'), ('HOTEL_HOSPITALITY', 'Hotel & Hospitality'), ('SCHOOL_INSTITUTION', 'School / Institution'), ('EXPORT_AGENT', 'Export Agent'), ('NGO', 'NGO / Aid Agency'), ('OTHER', 'Other')], max_length=30, verbose_name='Buyer Type')),
                ('annual_procurement_budget_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Annual Budget (USD)')),
                ('delivery_addresses', models.JSONField(blank=True, default=list, verbose_name='Delivery Locations')),
            ],
            options={
                'verbose_name': 'Commercial Buyer Profile',
                'verbose_name_plural': 'Commercial Buyer Profiles',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=150, verbose_name='Farm Trading Name')),
                ('farm_size_hectares', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Farm Size (Hectares)')),
                ('farm_location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('farm_location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('certified_organic', models.BooleanField(default=False, verbose_name='Certified Organic')),
                ('gapps_certified', models.BooleanField(default=False, verbose_name='GAPPS Certified')),
                ('annual_production_tonnes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Approx Annual Yield (Tonnes)')),
                ('irrigation_type', models.CharField(choices=[('RAINFED', 'Rainfed'), ('DRIP', 'Drip Irrigation'), ('PIVOT', 'Pivot Irrigation'), ('FLOOD', 'Flood Irrigation')], max_length=30, verbose_name='Irrigation Type')),
            ],
            options={
                'verbose_name': 'Farm Profile',
                'verbose_name_plural': 'Farm Profiles',
                'ordering': ['farm_name'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('otp_code', models.CharField(max_length=6, verbose_name='OTP Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
            ],
            options={
                'verbose_name': 'Phone OTP',
                'verbose_name_plural': 'Phone OTPs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+263771234567'. Up to 12 digits allowed.", regex='^\\+263(77|78|71|73)\\d{7}$')], verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('role', models.CharField(choices=[('SMALLHOLDER_FARMER', 'Smallholder Farmer'), ('COMMERCIAL_FARMER', 'Commercial Farmer'), ('RETAIL_BUYER', 'Retail Buyer'), ('COMMERCIAL_BUYER', 'Commercial Buyer'), ('TRANSPORTER', 'Transporter'), ('ADMIN', 'Platform Admin')], max_length=30, verbose_name='User Role')),
                ('subscription_tier', models.CharField(choices=[('SEED', 'Seed Tier (Free)'), ('HARVEST', 'Harvest Tier ($5/month)'), ('ENTERPRISE', 'Enterprise Tier ($25/month)'), ('COMMERCIAL', 'Commercial Tier ($80/month)')], default='SEED', max_length=20, verbose_name='Subscription Tier')),
                ('kyc_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=20, verbose_name='KYC Verification Status')),
                ('national_id_photo', models.FileField(blank=True, null=True, upload_to='kyc/national_ids/', verbose_name='National ID Photo')),
                ('selfie_photo', models.FileField(blank=True, null=True, upload_to='kyc/selfies/', verbose_name='Selfie Photo')),
                ('business_registration_doc', models.FileField(blank=True, null=True, upload_to='kyc/business_docs/', verbose_name='Business Registration Document')),
                ('tax_clearance_doc', models.FileField(blank=True, null=True, upload_to='kyc/tax_docs/', verbose_name='Tax Clearance Document')),
                ('province', models.CharField(choices=[('HARARE', 'Harare'), ('BULAWAYO', 'Bulawayo'), ('MANICALAND', 'Manicaland'), ('MASHONALAND_CENTRAL', 'Mashonaland Central'), ('MASHONALAND_EAST', 'Mashonaland East'), ('MASHONALAND_WEST', 'Mashonaland West'), ('MASVINGO', 'Masvingo'), ('MATABELELAND_NORTH', 'Matabeleland North'), ('MATABELELAND_SOUTH', 'Matabeleland South'), ('MIDLANDS', 'Midlands')], max_length=50, verbose_name='Province')),
                ('district', models.CharField(max_length=100, verbose_name='District')),
                ('trust_score', models.FloatField(default=5.0, verbose_name='Trust Score')),
                ('is_commercially_approved', models.BooleanField(default=False, verbose_name='Approved for Commercial Trading')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff Member')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
