# Generated by Django 5.0.14 on 2026-06-11 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialbuyerprofile',
            name='preferred_commodities',
            field=models.ManyToManyField(blank=True, related_name='commercial_buyers', to='market_data.commodity', verbose_name='Preferred Commodities'),
        ),
        migrations.AddField(
            model_name='commercialbuyerprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'COMMERCIAL_BUYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_buyer_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='primary_commodities',
            field=models.ManyToManyField(blank=True, related_name='farms', to='market_data.commodity', verbose_name='Primary Commodities Grown'),
        ),
        migrations.AddField(
            model_name='farmprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role__in': ['SMALLHOLDER_FARMER', 'COMMERCIAL_FARMER']}, on_delete=django.db.models.deletion.CASCADE, related_name='farm_profile', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
