# Generated by Django 5.0.14 on 2026-06-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payout_account_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Payout Account Holder Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payout Bank Name'),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_channel',
            field=models.CharField(choices=[('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('telecash', 'TeleCash'), ('bank', 'Commercial Bank')], default='ecocash', max_length=20, verbose_name='Payout Channel'),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_destination',
            field=models.CharField(blank=True, max_length=100, verbose_name='Payout Account / Phone Number'),
        ),
    ]
