# Generated by Django 5.0.14 on 2026-06-11 19:46

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_qty_tonnes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Quantity (Tonnes)')),
                ('price_per_tonne_usd_cents', models.PositiveIntegerField(verbose_name='Contract Price per Tonne (USD cents)')),
                ('status', django_fsm.FSMField(default='AWARDED', max_length=50, verbose_name='Contract Status')),
                ('terms_text', models.TextField(verbose_name='Contract Terms & Conditions')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Commercial Buyer')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='market_data.commodity', verbose_name='Commodity')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Commercial Farmer')),
            ],
            options={
                'verbose_name': 'Bulk Contract',
                'verbose_name_plural': 'Bulk Contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_index', models.PositiveIntegerField(verbose_name='Milestone Index')),
                ('description', models.CharField(max_length=200, verbose_name='Milestone Milestone Description')),
                ('deposit_pct', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Payment Percentage (%)')),
                ('due_condition', models.CharField(max_length=250, verbose_name='Trigger/Condition to Pay')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.bulkcontract', verbose_name='Bulk Contract')),
            ],
            options={
                'verbose_name': 'Contract Milestone',
                'verbose_name_plural': 'Contract Milestones',
                'ordering': ['contract', 'milestone_index'],
            },
        ),
        migrations.CreateModel(
            name='ForwardContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_tonnes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity (Tonnes)')),
                ('delivery_date', models.DateField(verbose_name='Scheduled Delivery Date')),
                ('fixed_price_per_tonne_usd_cents', models.PositiveIntegerField(verbose_name='Fixed Price per Tonne (USD cents)')),
                ('deposit_pct', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Required Deposit (%)')),
                ('status', django_fsm.FSMField(default='DRAFT', max_length=50, verbose_name='Forward Contract Status')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Accepted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_forward_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forward_contracts', to='market_data.commodity', verbose_name='Commodity')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_forward_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Farmer')),
            ],
            options={
                'verbose_name': 'Forward Contract',
                'verbose_name_plural': 'Forward Contracts',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='contracts/documents/', verbose_name='Document File')),
                ('document_type', models.CharField(choices=[('SIGNED_PDF', 'Signed PDF Contract'), ('QUALITY_CERT', 'Quality Certificate'), ('DELIVERY_NOTE', 'Delivery Note'), ('OTHER', 'Other')], max_length=30, verbose_name='Document Type')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.bulkcontract', verbose_name='Bulk Contract')),
                ('forward_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.forwardcontract', verbose_name='Forward Contract')),
            ],
            options={
                'verbose_name': 'Contract Document',
                'verbose_name_plural': 'Contract Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_tonnes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Required (Tonnes)')),
                ('quality_spec', models.TextField(verbose_name='Quality Specifications')),
                ('delivery_district', models.CharField(max_length=100, verbose_name='Delivery District')),
                ('deadline', models.DateTimeField(verbose_name='RFQ Deadline')),
                ('status', django_fsm.FSMField(default='DRAFT', max_length=50, verbose_name='RFQ Status')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to=settings.AUTH_USER_MODEL, verbose_name='Commercial Buyer')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='market_data.commodity', verbose_name='Commodity')),
            ],
            options={
                'verbose_name': 'Request for Quotation',
                'verbose_name_plural': 'Requests for Quotations',
                'ordering': ['-deadline'],
            },
        ),
        migrations.AddField(
            model_name='bulkcontract',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.rfq', verbose_name='Originating RFQ'),
        ),
        migrations.CreateModel(
            name='RFQQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_tonne_usd_cents', models.PositiveIntegerField(verbose_name='Price per Tonne (USD cents)')),
                ('qty_tonnes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantity Offered (Tonnes)')),
                ('availability_date', models.DateField(verbose_name='Date of Availability')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Terms')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Is Accepted')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfq_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Commercial Farmer')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='contracts.rfq', verbose_name='RFQ')),
            ],
            options={
                'verbose_name': 'RFQ Quote',
                'verbose_name_plural': 'RFQ Quotes',
                'ordering': ['price_per_tonne_usd_cents'],
            },
        ),
        migrations.AddField(
            model_name='bulkcontract',
            name='winning_quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.rfqquote', verbose_name='Winning Quote'),
        ),
    ]
